defaults: &defaults
  root_prefix: /valera
  markets: 
    - BTC_USDT

  polling_sleep: 0.1
  maker_sleep: 0.1

  influx:
    collectors: 'upstream'
    orders_updater: 'processor'

  upstreams: 
    binance: 
      client: Valera::BinanceClient
    peatio:
      client: Peatio::Client::REST

  accounts:
    bargainer_bot:
      upstream: peatio
      credentials: bargainer_bot
    deep_stoner_bot:
      upstream: peatio
      credentials: deep_stoner_bot
    binance:
      upstream: binance
      credentials: binance

  drainers:
    binance_websocket:
      class: BinanceWebsocketDrainer
      account: binance
      upstream: binance

    peatio_websocket:
      class: PeatioWebsocketDrainer
      account: deep_stoner_bot
      upstream: peatio

    peatio_rest:
      class: PeatioRestDrainer
      account: deep_stoner_bot
      upstream: peatio

    peatio_balance_deep_stoner:
      class: PeatioAccountDrainer
      upstream: peatio
      account: deep_stoner_bot

    peatio_balance_bargainer:
      class: PeatioAccountDrainer
      upstream: peatio
      account: bargainer_bot

  strategies:
    deep_stoner:
      class: DeepStonerStrategy
      comment: Глубокий наполнятель стакана
      account: deep_stoner_bot
      buyout_account: binance

    bargainer:
      class: BargainerStrategy
      comment: Проторговщик, торгует на малые объёмы но постоянно и сам с собой
      account: bargainer_bot

development:
  <<: *defaults
  polling_sleep: 1
  maker_sleep: 1
staging:
  <<: *defaults
production:
  <<: *defaults
test:
  <<: *defaults
  root_prefix: /valera
  markets: ["BTC_USDT"]

  upstreams: 
    binance:
      client: Valera::BinanceClient
    peatio:
      client: Peatio::Client::REST

  accounts:
    peatio1:
      upstream: peatio
      credentials: 
        access_key: test
        secret_key: text
    peatio2:
      upstream: peatio
      credentials: 
        access_key: test
        secret_key: text
    binance:
      upstream: binance
      credentials: 
        access_key: test
        secret_key: text

  drainers: {}
  strategies: {}
