defaults: &defaults
  # markets: ["BTC:USDT", "BTC:MCR", "ETH:BTC", "ETH:USDT", "ETH:MCR", "USDT:MCR"]
  markets: ["BTC:USDT"]
  universes:
    stoner:
      class: StoneStrategy
      comment: Камни (danil@orionet.ru)
      credentials: danil_orionet_ru
    bargainer:
      class: BargainerStrategy
      comment: Проторговщик, торгует на малые объёмы но постоянно и сам с собой (danil@onelec.ru)
      credentials: danil_onelec_ru
development:
  <<: *defaults
staging:
  <<: *defaults
production:
  <<: *defaults
test:
  <<: *defaults
