defaults: &defaults
  # markets: ["BTC:USDT", "BTC:MCR", "ETH:BTC", "ETH:USDT", "ETH:MCR", "USDT:MCR"]
  markets: ["BTC:USDT"]
  bots:
    stoner:
      description: Камни (danil@orionet.ru)
      credentials: danil_orionet_ru
      settings:
        global:
          ask_place_threshold: 0.05
          bid_place_threshold: -0.05
        markets:
          ETH_BTC:       
            volume: 0.0001
          ETH_USDT:      
            volume: 0.0001
          BTC_USDT:      
            volume: 0.0001
          BTC_MCR:       
            volume: 0.0001
          ETH_MCR:       
            volume: 0.0001
          USD_TMCR:      
            volume: 1
    bargainer:
      description: Проторговщик, торгует на малые объёмы но постоянно и сам с собой (danil@onelec.ru)
      credentials: danil_onelec_ru
      settings:
        global:
          ask_place_threshold: 0.001
          bid_place_threshold: -0.001
        markets:
          ETH_BTC:       
            volume: 0.0001
          ETH_USDT:      
            volume: 0.0001
          BTC_USDT:      
            volume: 0.0001
          BTC_MCR:       
            volume: 0.0001
          ETH_MCR:       
            volume: 0.0001
          USD_TMCR:      
            volume: 1

development:
  <<: *defaults
staging:
  <<: *defaults
production:
  <<: *defaults
test:
  <<: *defaults
