defaults: &defaults
  root_prefix: /valera
  # markets_ ["BTC_USDT", "BTC_MCR", "ETH_BTC", "ETH_USDT", "ETH_MCR", "USDT_MCR"]
  # binance_symbol: symbol.upcase.gsub('MCR', 'RUB')
  markets: 
    - BTC_USDT
    - quote: UUU
      base: BBB
      binance_symbol: BTCUSDT

  polling_sleep: 0.1
  maker_sleep: 0.1

  influx:
    collectors: 'upstream'
    orders_updater: 'processor'

  upstreams: 
    binance: {}
    peatio:
      credential_client: Peatio::Client::REST

  accounts:
    bargainer_bot:
      upstream: peatio
      credentials: bargainer_bot
    deep_stoner_bot:
      upstream: peatio
      credentials: deep_stoner_bot
    binance:
      upstream: binance

  drainers:
    binance_websocket:
      class: BinanceWebsocketDrainer
      account: binance
      upstream: binance

    peatio_websocket:
      class: PeatioWebsocketDrainer
      account: deep_stoner_bot
      upstream: peatio

    peatio_rest:
      class: PeatioRestDrainer
      account: deep_stoner_bot
      upstream: peatio

    peatio_balance_deep_stoner:
      class: PeatioAccountDrainer
      upstream: peatio
      account: deep_stoner_bot

    peatio_balance_bargainer:
      class: PeatioAccountDrainer
      upstream: peatio
      account: bargainer_bot

  strategies:
    deep_stoner:
      class: DeepStonerStrategy
      comment: Глубокий наполнятель стакана
      account: deep_stoner_bot

    bargainer:
      class: BargainerStrategy
      comment: Проторговщик, торгует на малые объёмы но постоянно и сам с собой
      account: bargainer_bot

development:
  <<: *defaults
  polling_sleep: 1
  maker_sleep: 1
staging:
  <<: *defaults
production:
  <<: *defaults
test:
  <<: *defaults
  root_prefix: /valera
  markets: ["BTC_USDT"]

  upstreams: 
    binance: {}
    peatio: {}

  accounts:
    peatio1:
      upstream: peatio
    peatio2:
      upstream: peatio
    binance:
      upstream: binance

  drainers: {}
  strategies: {}
