defaults: &defaults
  root_prefix: /valera
  currencies:
    BTC:
      precision: 8
    USDT:
      precision: 2
    BBB: 
      precision: 8
    UUU: 
      precision: 2
  markets: 
    - BTC_USDT
    - quote: UUU
      base: BBB
      binance_symbol: BTCUSDT

  polling_sleep: 0.1
  maker_sleep: 0.1

  influx:
    collectors: 'upstream'
    orders_updater: 'processor'

  upstreams: 
    binance: 
      client: Valera::BinanceClient
    peatio:
      client: Valera::PeatioClient

  accounts:
    bargainer_bot:
      upstream: peatio
      credentials: bargainer_bot
    deep_stoner_bot:
      upstream: peatio
      credentials: deep_stoner_bot
    binance:
      upstream: binance
      credentials: binance

  drainers:
    binance_websocket:
      class: BinanceWebsocketDrainer
      account: binance

    peatio_websocket:
      class: PeatioWebsocketDrainer
      account: deep_stoner_bot

    peatio_rest:
      class: PeatioRestDrainer
      account: deep_stoner_bot

    peatio_balance_deep_stoner:
      class: AccountDrainer
      account: deep_stoner_bot
      interval: 1

    peatio_balance_bargainer:
      class: AccountDrainer
      account: bargainer_bot
      interval: 1

    binance_account:
      class: AccountDrainer
      account: binance
      interval: 30

    binance_userdata_websocket:
      class: BinanceUserdataWebsocketDrainer
      account: binance

  strategies:
    deep_stoner:
      class: DeepStonerStrategy
      comment: Арбитражник - глубокий наполнятель стакана
      account: deep_stoner_bot
      buyout_account: binance
      source_account: binance

    bargainer:
      class: BargainerStrategy
      comment: Проторговщик, торгует на малые объёмы, иногда так получается что сделки закрываются на самого себя
      account: bargainer_bot
      source_account: binance

development:
  <<: *defaults
  polling_sleep: 1
  maker_sleep: 1
staging:
  <<: *defaults
production:
  <<: *defaults
test:
  <<: *defaults
  root_prefix: /valera
  markets: ["BTC_USDT"]
  drainers:
    binance_websocket:
      class: BinanceWebsocketDrainer
      account: binance

    peatio_websocket:
      class: PeatioWebsocketDrainer
      account: peatio1

    peatio_rest:
      class: PeatioRestDrainer
      account: peatio1

    peatio_balance_deep_stoner:
      class: AccountDrainer
      account: peatio1

    peatio_balance_bargainer:
      class: AccountDrainer
      account: binance

  upstreams: 
    binance:
      client: Valera::BinanceClient
    peatio:
      client: Valera::PeatioClient

  accounts:
    peatio1:
      upstream: peatio
      credentials: 
        access_key: test
        secret_key: text
    peatio2:
      upstream: peatio
      credentials: 
        access_key: test
        secret_key: text
    binance:
      upstream: binance
      credentials: 
        name: :binance
        api_key: test
        secret_key: test

  strategies:
    deep_stoner:
      class: DeepStonerStrategy
      comment: Арбитражник - глубокий наполнятель стакана
      account: peatio1
      buyout_account: binance

    bargainer:
      class: BargainerStrategy
      comment: Проторговщик, торгует на малые объёмы, иногда так получается что сделки закрываются на самого себя
      account: peatio2
