defaults: &defaults
  # markets: ["BTC:USDT", "BTC:MCR", "ETH:BTC", "ETH:USDT", "ETH:MCR", "USDT:MCR"]
  markets: ["BTC:USDT"]
  bots:
    stoner:
      description: Камни (danil@orionet.ru)
      credentials: danil_orionet_ru
      global_settings:
        ask_place_threshold: 0.05
        bid_place_threshold: -0.05
    bargainer:
      description: Проторговщик, торгует на малые объёмы но постоянно и сам с собой (danil@onelec.ru)
      credentials: danil_onelec_ru
      global_settings:
        ask_place_threshold: 0.001
        bid_place_threshold: -0.001

development:
  <<: *defaults
staging:
  <<: *defaults
production:
  <<: *defaults
test:
  <<: *defaults
